server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          baseinc:
            provider:      "baseinc"
            client-name:   "BaseInc"
            client-id:     "[env]"
            client-secret: "[env]"
            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read_users 
              - read_users_mail
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "post"
        provider:          baseinc:
            authorization-uri: "https://api.thebase.in/1/oauth/authorize" 
            token-uri:         "https://api.thebase.in/1/oauth/token"
            user-info-uri:     "https://api.thebase.in/1/users/me"
